

```python
#### python의 slicing ####

import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a[1:3]) # 1번째부터 3번째(제외)까지
print(a[-1]) # -1은 마지막 원소
a[0:2] = 9 # 0번째부터 1번째까지
print(a)

print()

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(b[:, 1]) # 모든 행의 1번째 원소
print(b[-1]) # 마지막 행
print(b[-1, :]) # 마지막 행
print(b[-1, ...]) # :을 ...으로 표현 가능
print(b[0:2, :]) # 0~1행
print(b[:, 0:-1]) # 모든 행의 마지막 원소를 제외한 행렬
```

    [2 3]
    5
    [9 9 3 4 5]
    
    [ 2  6 10]
    [ 9 10 11 12]
    [ 9 10 11 12]
    [ 9 10 11 12]
    [[1 2 3 4]
     [5 6 7 8]]
    [[ 1  2  3]
     [ 5  6  7]
     [ 9 10 11]]



```python
#### 파일에서 데이터 읽어오기 ####
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

# 파일에서 데이터 읽어오기
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] # 마지막 열을 제외한 데이터
y_data = xy[:, [-1]] # 마지막 열 (-1만 쓰면 한 행으로 반환)

# 데이터 확인
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "\nCost:", cost_val, "\nPrediction:\n", hy_val, "\n")

# 테스트 : 내 점수 예상
print("Your score will be", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))
```

    (6, 3) [[ 73.  80.  75.]
     [ 93.  88.  93.]
     [ 89.  91.  90.]
     [ 96.  98. 100.]
     [ 73.  66.  70.]
     [ 53.  46.  55.]] 6
    (6, 1) [[152.]
     [185.]
     [180.]
     [196.]
     [142.]
     [101.]]
    0 
    Cost: 133861.69 
    Prediction:
     [[-192.43304]
     [-229.125  ]
     [-227.11491]
     [-245.61145]
     [-175.42165]
     [-125.97296]] 
    
    100 
    Cost: 6.2110515 
    Prediction:
     [[151.01865 ]
     [183.73029 ]
     [179.65161 ]
     [197.34727 ]
     [139.49582 ]
     [106.146225]] 
    
    200 
    Cost: 6.1322904 
    Prediction:
     [[151.05896]
     [183.71378]
     [179.6705 ]
     [197.3479 ]
     [139.48343]
     [106.09856]] 
    
    ...
    
    1800 
    Cost: 5.1854887 
    Prediction:
     [[151.55475 ]
     [183.52074 ]
     [179.91104 ]
     [197.32281 ]
     [139.37563 ]
     [105.481224]] 
    
    1900 
    Cost: 5.140099 
    Prediction:
     [[151.57808 ]
     [183.51231 ]
     [179.9229  ]
     [197.31947 ]
     [139.37346 ]
     [105.450134]] 
    
    2000 
    Cost: 5.09586 
    Prediction:
     [[151.6007 ]
     [183.50421]
     [179.93445]
     [197.31598]
     [139.3717 ]
     [105.41976]] 
    
    Your score will be [[187.06743]]
    Other scores will be [[182.71024]
     [172.87012]]



```python
#### Queue runners 이용 ####
# 파일이 너무 커서 메모리에 한번에 담을 수 없을 때 사용
import tensorflow as tf

# 파일 읽어오기
filename_queue = tf.train.string_input_producer(
    ['data/data-01-test-score.csv'], shuffle=False, name='filename_queue') # 배열에 여러개 파일 가능
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# 결과 디코딩
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# csv의 batch 수집
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "\nCost:", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# 실행 안됨. 원인은 아직 모르겠음..
```

    INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Expect 4 fields but have 3 in record 0
    	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", na_value="", use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2_1:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0)]]



    ---------------------------------------------------------------------------
    
    OutOfRangeError                           Traceback (most recent call last)
    
    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
       1321     try:
    -> 1322       return fn(*args)
       1323     except errors.OpError as e:


    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
       1306       return self._call_tf_sessionrun(
    -> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
       1308 


    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
       1408           self._session, options, feed_dict, fetch_list, target_list,
    -> 1409           run_metadata)
       1410     else:


    OutOfRangeError: FIFOQueue '_69_batch_5/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
    	 [[Node: batch_5 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_5/fifo_queue, batch_5/n)]]


​    
    During handling of the above exception, another exception occurred:


    OutOfRangeError                           Traceback (most recent call last)
    
    <ipython-input-36-14fe46ff6f2d> in <module>()
         35 
         36 for step in range(2001):
    ---> 37     x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
         38     cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
         39                                    feed_dict={X: x_batch, Y: y_batch})


    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
        898     try:
        899       result = self._run(None, fetches, feed_dict, options_ptr,
    --> 900                          run_metadata_ptr)
        901       if run_metadata:
        902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)


    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
       1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
       1134       results = self._do_run(handle, final_targets, final_fetches,
    -> 1135                              feed_dict_tensor, options, run_metadata)
       1136     else:
       1137       results = []


    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
       1314     if handle is None:
       1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
    -> 1316                            run_metadata)
       1317     else:
       1318       return self._do_call(_prun_fn, handle, feeds, fetches)


    C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
       1333         except KeyError:
       1334           pass
    -> 1335       raise type(e)(node_def, op, message)
       1336 
       1337   def _extend_graph(self):


    OutOfRangeError: FIFOQueue '_69_batch_5/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
    	 [[Node: batch_5 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_5/fifo_queue, batch_5/n)]]
    
    Caused by op 'batch_5', defined at:
      File "C:\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
        app.launch_new_instance()
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
        app.start()
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
        self.io_loop.start()
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
        self.asyncio_loop.run_forever()
      File "C:\Anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 421, in run_forever
        self._run_once()
      File "C:\Anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 1425, in _run_once
        handle._run()
      File "C:\Anaconda3\envs\tensorflow\lib\asyncio\events.py", line 127, in _run
        self._callback(*self._args)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
        handler_func(fileobj, events)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
        return fn(*args, **kwargs)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
        self._handle_recv()
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
        self._run_callback(callback, msg)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
        callback(*args, **kwargs)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
        return fn(*args, **kwargs)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
        handler(stream, idents, msg)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
        user_expressions, allow_stdin)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
        res = shell.run_cell(code, store_history=store_history, silent=silent)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
        return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
        raw_cell, store_history, silent, shell_futures)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
        interactivity=interactivity, compiler=compiler, result=result)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
        if self.run_code(code, result):
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-36-14fe46ff6f2d>", line 16, in <module>
        train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\input.py", line 988, in batch
        name=name)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\input.py", line 762, in _batch
        dequeued = queue.dequeue_many(batch_size, name=name)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 483, in dequeue_many
        self._queue_ref, n=n, component_types=self._dtypes, name=name)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3799, in queue_dequeue_many_v2
        component_types=component_types, timeout_ms=timeout_ms, name=name)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
        op_def=op_def)
      File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
    
    OutOfRangeError (see above for traceback): FIFOQueue '_69_batch_5/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
    	 [[Node: batch_5 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_5/fifo_queue, batch_5/n)]]


